from .user import (
    UserBase,
    UserCreate,
    UserCreateOdoo,
    UserUpdate,
    UserResponse,
    UserInDB,
    Token,
    TokenPayload,
)
from .document import (
    DocumentBase,
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentDetail,
    DocumentVersionResponse,
    DocumentListResponse,
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    CategoryBase,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
)
from .search import (
    SearchQuery,
    SearchResult,
    SearchResponse,
    SearchSuggestion,
)
from .generate import (
    DocumentType,
    OutputLanguage,
    GenerateRequest,
    GenerateJobStatus,
    GenerateJobResponse,
    GenerateTemplateInfo,
    GenerateTemplatesResponse,
    GeneratedContent,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserCreateOdoo",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "Token",
    "TokenPayload",
    # Document schemas
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentDetail",
    "DocumentVersionResponse",
    "DocumentListResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    # Search schemas
    "SearchQuery",
    "SearchResult",
    "SearchResponse",
    "SearchSuggestion",
    # Generate schemas
    "DocumentType",
    "OutputLanguage",
    "GenerateRequest",
    "GenerateJobStatus",
    "GenerateJobResponse",
    "GenerateTemplateInfo",
    "GenerateTemplatesResponse",
    "GeneratedContent",
]
